// Auto-generated by scripts/generateMissingBeastArt.ts.
// Do not hand-edit unless the generation pipeline is unavailable.
export const generatedBeastAssetManifest = [
  { key: 'beast_portrait_thach_giap_thu_01', path: 'assets/beasts/beast_portrait_thach_giap_thu_01.png', type: 'image' },
  { key: 'beast_portrait_thanh_lang_01', path: 'assets/beasts/beast_portrait_thanh_lang_01.png', type: 'image' },
  { key: 'beast_portrait_xich_nha_thu_01', path: 'assets/beasts/beast_portrait_xich_nha_thu_01.png', type: 'image' },
] as const;
